//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 02:49:48 PM EET 
//


package com.example.finagoxmltocsv.Objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BuyerPartyDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BuyerPartyDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BuyerPartyIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BuyerOrganisationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BuyerPostalAddressDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BuyerStreetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BuyerTownName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BuyerPostCodeIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuyerPartyDetails", propOrder = {
    "buyerPartyIdentifier",
    "buyerOrganisationName",
    "buyerPostalAddressDetails"
})
public class BuyerPartyDetails {

    @XmlElement(name = "BuyerPartyIdentifier")
    protected String buyerPartyIdentifier;
    @XmlElement(name = "BuyerOrganisationName")
    protected String buyerOrganisationName;
    @XmlElement(name = "BuyerPostalAddressDetails")
    protected BuyerPartyDetails.BuyerPostalAddressDetails buyerPostalAddressDetails;

    /**
     * Gets the value of the buyerPartyIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerPartyIdentifier() {
        return buyerPartyIdentifier;
    }

    /**
     * Sets the value of the buyerPartyIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerPartyIdentifier(String value) {
        this.buyerPartyIdentifier = value;
    }

    /**
     * Gets the value of the buyerOrganisationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerOrganisationName() {
        return buyerOrganisationName;
    }

    /**
     * Sets the value of the buyerOrganisationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerOrganisationName(String value) {
        this.buyerOrganisationName = value;
    }

    /**
     * Gets the value of the buyerPostalAddressDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BuyerPartyDetails.BuyerPostalAddressDetails }
     *     
     */
    public BuyerPartyDetails.BuyerPostalAddressDetails getBuyerPostalAddressDetails() {
        return buyerPostalAddressDetails;
    }

    /**
     * Sets the value of the buyerPostalAddressDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyerPartyDetails.BuyerPostalAddressDetails }
     *     
     */
    public void setBuyerPostalAddressDetails(BuyerPartyDetails.BuyerPostalAddressDetails value) {
        this.buyerPostalAddressDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BuyerStreetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BuyerTownName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BuyerPostCodeIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "buyerStreetName",
        "buyerTownName",
        "buyerPostCodeIdentifier",
        "countryCode"
    })
    public static class BuyerPostalAddressDetails {

        @XmlElement(name = "BuyerStreetName")
        protected String buyerStreetName;
        @XmlElement(name = "BuyerTownName")
        protected String buyerTownName;
        @XmlElement(name = "BuyerPostCodeIdentifier")
        protected String buyerPostCodeIdentifier;
        @XmlElement(name = "CountryCode")
        protected String countryCode;

        /**
         * Gets the value of the buyerStreetName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBuyerStreetName() {
            return buyerStreetName;
        }

        /**
         * Sets the value of the buyerStreetName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBuyerStreetName(String value) {
            this.buyerStreetName = value;
        }

        /**
         * Gets the value of the buyerTownName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBuyerTownName() {
            return buyerTownName;
        }

        /**
         * Sets the value of the buyerTownName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBuyerTownName(String value) {
            this.buyerTownName = value;
        }

        /**
         * Gets the value of the buyerPostCodeIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBuyerPostCodeIdentifier() {
            return buyerPostCodeIdentifier;
        }

        /**
         * Sets the value of the buyerPostCodeIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBuyerPostCodeIdentifier(String value) {
            this.buyerPostCodeIdentifier = value;
        }

        /**
         * Gets the value of the countryCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryCode() {
            return countryCode;
        }

        /**
         * Sets the value of the countryCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryCode(String value) {
            this.countryCode = value;
        }

    }

}
