//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 02:49:48 PM EET 
//


package com.example.finagoxmltocsv.Objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeliveryPartyDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeliveryPartyDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeliveryOrganisationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DeliveryPostalAddressDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DeliveryStreetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DeliveryTownName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DeliveryPostCodeIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryPartyDetails", propOrder = {
    "deliveryOrganisationName",
    "deliveryPostalAddressDetails"
})
public class DeliveryPartyDetails {

    @XmlElement(name = "DeliveryOrganisationName")
    protected String deliveryOrganisationName;
    @XmlElement(name = "DeliveryPostalAddressDetails")
    protected DeliveryPartyDetails.DeliveryPostalAddressDetails deliveryPostalAddressDetails;

    /**
     * Gets the value of the deliveryOrganisationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryOrganisationName() {
        return deliveryOrganisationName;
    }

    /**
     * Sets the value of the deliveryOrganisationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryOrganisationName(String value) {
        this.deliveryOrganisationName = value;
    }

    /**
     * Gets the value of the deliveryPostalAddressDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryPartyDetails.DeliveryPostalAddressDetails }
     *     
     */
    public DeliveryPartyDetails.DeliveryPostalAddressDetails getDeliveryPostalAddressDetails() {
        return deliveryPostalAddressDetails;
    }

    /**
     * Sets the value of the deliveryPostalAddressDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryPartyDetails.DeliveryPostalAddressDetails }
     *     
     */
    public void setDeliveryPostalAddressDetails(DeliveryPartyDetails.DeliveryPostalAddressDetails value) {
        this.deliveryPostalAddressDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DeliveryStreetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DeliveryTownName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DeliveryPostCodeIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deliveryStreetName",
        "deliveryTownName",
        "deliveryPostCodeIdentifier",
        "countryCode"
    })
    public static class DeliveryPostalAddressDetails {

        @XmlElement(name = "DeliveryStreetName")
        protected String deliveryStreetName;
        @XmlElement(name = "DeliveryTownName")
        protected String deliveryTownName;
        @XmlElement(name = "DeliveryPostCodeIdentifier")
        protected String deliveryPostCodeIdentifier;
        @XmlElement(name = "CountryCode")
        protected String countryCode;

        /**
         * Gets the value of the deliveryStreetName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeliveryStreetName() {
            return deliveryStreetName;
        }

        /**
         * Sets the value of the deliveryStreetName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeliveryStreetName(String value) {
            this.deliveryStreetName = value;
        }

        /**
         * Gets the value of the deliveryTownName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeliveryTownName() {
            return deliveryTownName;
        }

        /**
         * Sets the value of the deliveryTownName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeliveryTownName(String value) {
            this.deliveryTownName = value;
        }

        /**
         * Gets the value of the deliveryPostCodeIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeliveryPostCodeIdentifier() {
            return deliveryPostCodeIdentifier;
        }

        /**
         * Sets the value of the deliveryPostCodeIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeliveryPostCodeIdentifier(String value) {
            this.deliveryPostCodeIdentifier = value;
        }

        /**
         * Gets the value of the countryCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryCode() {
            return countryCode;
        }

        /**
         * Sets the value of the countryCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryCode(String value) {
            this.countryCode = value;
        }

    }

}
