//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 02:49:48 PM EET 
//


package com.example.finagoxmltocsv.Objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BuyerPartyDetails" type="{}BuyerPartyDetails" minOccurs="0"/>
 *         &lt;element name="DeliveryPartyDetails" type="{}DeliveryPartyDetails" minOccurs="0"/>
 *         &lt;element name="InvoiceDetails" type="{}InvoiceDetails" minOccurs="0"/>
 *         &lt;element name="InvoiceRow" type="{}InvoiceRow" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "buyerPartyDetails",
    "deliveryPartyDetails",
    "invoiceDetails",
    "invoiceRow"
})
@XmlRootElement(name = "Finvoice")
public class Finvoice {

    @XmlElement(name = "BuyerPartyDetails")
    protected BuyerPartyDetails buyerPartyDetails;
    @XmlElement(name = "DeliveryPartyDetails")
    protected DeliveryPartyDetails deliveryPartyDetails;
    @XmlElement(name = "InvoiceDetails")
    protected InvoiceDetails invoiceDetails;
    @XmlElement(name = "InvoiceRow")
    protected List<InvoiceRow> invoiceRow;
    @XmlAttribute(name = "Version", required = true)
    protected String version;

    /**
     * Gets the value of the buyerPartyDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BuyerPartyDetails }
     *     
     */
    public BuyerPartyDetails getBuyerPartyDetails() {
        return buyerPartyDetails;
    }

    /**
     * Sets the value of the buyerPartyDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyerPartyDetails }
     *     
     */
    public void setBuyerPartyDetails(BuyerPartyDetails value) {
        this.buyerPartyDetails = value;
    }

    /**
     * Gets the value of the deliveryPartyDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryPartyDetails }
     *     
     */
    public DeliveryPartyDetails getDeliveryPartyDetails() {
        return deliveryPartyDetails;
    }

    /**
     * Sets the value of the deliveryPartyDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryPartyDetails }
     *     
     */
    public void setDeliveryPartyDetails(DeliveryPartyDetails value) {
        this.deliveryPartyDetails = value;
    }

    /**
     * Gets the value of the invoiceDetails property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDetails }
     *     
     */
    public InvoiceDetails getInvoiceDetails() {
        return invoiceDetails;
    }

    /**
     * Sets the value of the invoiceDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDetails }
     *     
     */
    public void setInvoiceDetails(InvoiceDetails value) {
        this.invoiceDetails = value;
    }

    /**
     * Gets the value of the invoiceRow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceRow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceRow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoiceRow }
     * 
     * 
     */
    public List<InvoiceRow> getInvoiceRow() {
        if (invoiceRow == null) {
            invoiceRow = new ArrayList<InvoiceRow>();
        }
        return this.invoiceRow;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
