//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 02:49:48 PM EET 
//


package com.example.finagoxmltocsv.Objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for InvoiceDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InvoiceTypeCode" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="CodeListAgencyIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InvoiceDate" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Format" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InvoiceTotalVatExcludedAmount" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="AmountCurrencyIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InvoiceTotalVatAmount" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="AmountCurrencyIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InvoiceTotalVatIncludedAmount" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="AmountCurrencyIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InvoiceFreeText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PaymentTermsDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="InvoiceDueDate" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Format" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PaymentOverDueFineDetails" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PaymentOverDueFinePercent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceDetails", propOrder = {
    "invoiceTypeCode",
    "invoiceDate",
    "invoiceTotalVatExcludedAmount",
    "invoiceTotalVatAmount",
    "invoiceTotalVatIncludedAmount",
    "invoiceFreeText",
    "paymentTermsDetails"
})
public class InvoiceDetails {

    @XmlElement(name = "InvoiceTypeCode")
    protected InvoiceDetails.InvoiceTypeCode invoiceTypeCode;
    @XmlElement(name = "InvoiceDate")
    protected InvoiceDetails.InvoiceDate invoiceDate;
    @XmlElement(name = "InvoiceTotalVatExcludedAmount")
    protected InvoiceDetails.InvoiceTotalVatExcludedAmount invoiceTotalVatExcludedAmount;
    @XmlElement(name = "InvoiceTotalVatAmount")
    protected InvoiceDetails.InvoiceTotalVatAmount invoiceTotalVatAmount;
    @XmlElement(name = "InvoiceTotalVatIncludedAmount")
    protected InvoiceDetails.InvoiceTotalVatIncludedAmount invoiceTotalVatIncludedAmount;
    @XmlElement(name = "InvoiceFreeText")
    protected String invoiceFreeText;
    @XmlElement(name = "PaymentTermsDetails")
    protected InvoiceDetails.PaymentTermsDetails paymentTermsDetails;

    /**
     * Gets the value of the invoiceTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDetails.InvoiceTypeCode }
     *     
     */
    public InvoiceDetails.InvoiceTypeCode getInvoiceTypeCode() {
        return invoiceTypeCode;
    }

    /**
     * Sets the value of the invoiceTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDetails.InvoiceTypeCode }
     *     
     */
    public void setInvoiceTypeCode(InvoiceDetails.InvoiceTypeCode value) {
        this.invoiceTypeCode = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDetails.InvoiceDate }
     *     
     */
    public InvoiceDetails.InvoiceDate getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDetails.InvoiceDate }
     *     
     */
    public void setInvoiceDate(InvoiceDetails.InvoiceDate value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the invoiceTotalVatExcludedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDetails.InvoiceTotalVatExcludedAmount }
     *     
     */
    public InvoiceDetails.InvoiceTotalVatExcludedAmount getInvoiceTotalVatExcludedAmount() {
        return invoiceTotalVatExcludedAmount;
    }

    /**
     * Sets the value of the invoiceTotalVatExcludedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDetails.InvoiceTotalVatExcludedAmount }
     *     
     */
    public void setInvoiceTotalVatExcludedAmount(InvoiceDetails.InvoiceTotalVatExcludedAmount value) {
        this.invoiceTotalVatExcludedAmount = value;
    }

    /**
     * Gets the value of the invoiceTotalVatAmount property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDetails.InvoiceTotalVatAmount }
     *     
     */
    public InvoiceDetails.InvoiceTotalVatAmount getInvoiceTotalVatAmount() {
        return invoiceTotalVatAmount;
    }

    /**
     * Sets the value of the invoiceTotalVatAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDetails.InvoiceTotalVatAmount }
     *     
     */
    public void setInvoiceTotalVatAmount(InvoiceDetails.InvoiceTotalVatAmount value) {
        this.invoiceTotalVatAmount = value;
    }

    /**
     * Gets the value of the invoiceTotalVatIncludedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDetails.InvoiceTotalVatIncludedAmount }
     *     
     */
    public InvoiceDetails.InvoiceTotalVatIncludedAmount getInvoiceTotalVatIncludedAmount() {
        return invoiceTotalVatIncludedAmount;
    }

    /**
     * Sets the value of the invoiceTotalVatIncludedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDetails.InvoiceTotalVatIncludedAmount }
     *     
     */
    public void setInvoiceTotalVatIncludedAmount(InvoiceDetails.InvoiceTotalVatIncludedAmount value) {
        this.invoiceTotalVatIncludedAmount = value;
    }

    /**
     * Gets the value of the invoiceFreeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceFreeText() {
        return invoiceFreeText;
    }

    /**
     * Sets the value of the invoiceFreeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceFreeText(String value) {
        this.invoiceFreeText = value;
    }

    /**
     * Gets the value of the paymentTermsDetails property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDetails.PaymentTermsDetails }
     *     
     */
    public InvoiceDetails.PaymentTermsDetails getPaymentTermsDetails() {
        return paymentTermsDetails;
    }

    /**
     * Sets the value of the paymentTermsDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDetails.PaymentTermsDetails }
     *     
     */
    public void setPaymentTermsDetails(InvoiceDetails.PaymentTermsDetails value) {
        this.paymentTermsDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="Format" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class InvoiceDate {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Format")
        protected String format;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormat() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormat(String value) {
            this.format = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="AmountCurrencyIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class InvoiceTotalVatAmount {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "AmountCurrencyIdentifier")
        protected String amountCurrencyIdentifier;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the amountCurrencyIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmountCurrencyIdentifier() {
            return amountCurrencyIdentifier;
        }

        /**
         * Sets the value of the amountCurrencyIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmountCurrencyIdentifier(String value) {
            this.amountCurrencyIdentifier = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="AmountCurrencyIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class InvoiceTotalVatExcludedAmount {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "AmountCurrencyIdentifier")
        protected String amountCurrencyIdentifier;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the amountCurrencyIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmountCurrencyIdentifier() {
            return amountCurrencyIdentifier;
        }

        /**
         * Sets the value of the amountCurrencyIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmountCurrencyIdentifier(String value) {
            this.amountCurrencyIdentifier = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="AmountCurrencyIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class InvoiceTotalVatIncludedAmount {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "AmountCurrencyIdentifier")
        protected String amountCurrencyIdentifier;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the amountCurrencyIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmountCurrencyIdentifier() {
            return amountCurrencyIdentifier;
        }

        /**
         * Sets the value of the amountCurrencyIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmountCurrencyIdentifier(String value) {
            this.amountCurrencyIdentifier = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="CodeListAgencyIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class InvoiceTypeCode {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "CodeListAgencyIdentifier")
        protected String codeListAgencyIdentifier;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the codeListAgencyIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodeListAgencyIdentifier() {
            return codeListAgencyIdentifier;
        }

        /**
         * Sets the value of the codeListAgencyIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodeListAgencyIdentifier(String value) {
            this.codeListAgencyIdentifier = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="InvoiceDueDate" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Format" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PaymentOverDueFineDetails" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PaymentOverDueFinePercent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "invoiceDueDate",
        "paymentOverDueFineDetails"
    })
    public static class PaymentTermsDetails {

        @XmlElement(name = "InvoiceDueDate")
        protected InvoiceDetails.PaymentTermsDetails.InvoiceDueDate invoiceDueDate;
        @XmlElement(name = "PaymentOverDueFineDetails")
        protected InvoiceDetails.PaymentTermsDetails.PaymentOverDueFineDetails paymentOverDueFineDetails;

        /**
         * Gets the value of the invoiceDueDate property.
         * 
         * @return
         *     possible object is
         *     {@link InvoiceDetails.PaymentTermsDetails.InvoiceDueDate }
         *     
         */
        public InvoiceDetails.PaymentTermsDetails.InvoiceDueDate getInvoiceDueDate() {
            return invoiceDueDate;
        }

        /**
         * Sets the value of the invoiceDueDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link InvoiceDetails.PaymentTermsDetails.InvoiceDueDate }
         *     
         */
        public void setInvoiceDueDate(InvoiceDetails.PaymentTermsDetails.InvoiceDueDate value) {
            this.invoiceDueDate = value;
        }

        /**
         * Gets the value of the paymentOverDueFineDetails property.
         * 
         * @return
         *     possible object is
         *     {@link InvoiceDetails.PaymentTermsDetails.PaymentOverDueFineDetails }
         *     
         */
        public InvoiceDetails.PaymentTermsDetails.PaymentOverDueFineDetails getPaymentOverDueFineDetails() {
            return paymentOverDueFineDetails;
        }

        /**
         * Sets the value of the paymentOverDueFineDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link InvoiceDetails.PaymentTermsDetails.PaymentOverDueFineDetails }
         *     
         */
        public void setPaymentOverDueFineDetails(InvoiceDetails.PaymentTermsDetails.PaymentOverDueFineDetails value) {
            this.paymentOverDueFineDetails = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Format" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class InvoiceDueDate {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Format")
            protected String format;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the format property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFormat() {
                return format;
            }

            /**
             * Sets the value of the format property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFormat(String value) {
                this.format = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PaymentOverDueFinePercent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "paymentOverDueFinePercent"
        })
        public static class PaymentOverDueFineDetails {

            @XmlElement(name = "PaymentOverDueFinePercent")
            protected String paymentOverDueFinePercent;

            /**
             * Gets the value of the paymentOverDueFinePercent property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPaymentOverDueFinePercent() {
                return paymentOverDueFinePercent;
            }

            /**
             * Sets the value of the paymentOverDueFinePercent property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPaymentOverDueFinePercent(String value) {
                this.paymentOverDueFinePercent = value;
            }

        }

    }

}
