//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 02:49:48 PM EET 
//


package com.example.finagoxmltocsv.Objects;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.finagoxmltocsv.Objects package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.finagoxmltocsv.Objects
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceRow }
     * 
     */
    public InvoiceRow createInvoiceRow() {
        return new InvoiceRow();
    }

    /**
     * Create an instance of {@link InvoiceDetails }
     * 
     */
    public InvoiceDetails createInvoiceDetails() {
        return new InvoiceDetails();
    }

    /**
     * Create an instance of {@link InvoiceDetails.PaymentTermsDetails }
     * 
     */
    public InvoiceDetails.PaymentTermsDetails createInvoiceDetailsPaymentTermsDetails() {
        return new InvoiceDetails.PaymentTermsDetails();
    }

    /**
     * Create an instance of {@link DeliveryPartyDetails }
     * 
     */
    public DeliveryPartyDetails createDeliveryPartyDetails() {
        return new DeliveryPartyDetails();
    }

    /**
     * Create an instance of {@link BuyerPartyDetails }
     * 
     */
    public BuyerPartyDetails createBuyerPartyDetails() {
        return new BuyerPartyDetails();
    }

    /**
     * Create an instance of {@link Finvoice }
     * 
     */
    public Finvoice createFinvoice() {
        return new Finvoice();
    }

    /**
     * Create an instance of {@link InvoiceRow.OrderedQuantity }
     * 
     */
    public InvoiceRow.OrderedQuantity createInvoiceRowOrderedQuantity() {
        return new InvoiceRow.OrderedQuantity();
    }

    /**
     * Create an instance of {@link InvoiceRow.UnitPriceAmount }
     * 
     */
    public InvoiceRow.UnitPriceAmount createInvoiceRowUnitPriceAmount() {
        return new InvoiceRow.UnitPriceAmount();
    }

    /**
     * Create an instance of {@link InvoiceRow.RowVatAmount }
     * 
     */
    public InvoiceRow.RowVatAmount createInvoiceRowRowVatAmount() {
        return new InvoiceRow.RowVatAmount();
    }

    /**
     * Create an instance of {@link InvoiceRow.RowVatExcludedAmount }
     * 
     */
    public InvoiceRow.RowVatExcludedAmount createInvoiceRowRowVatExcludedAmount() {
        return new InvoiceRow.RowVatExcludedAmount();
    }

    /**
     * Create an instance of {@link InvoiceRow.RowAmount }
     * 
     */
    public InvoiceRow.RowAmount createInvoiceRowRowAmount() {
        return new InvoiceRow.RowAmount();
    }

    /**
     * Create an instance of {@link InvoiceDetails.InvoiceTypeCode }
     * 
     */
    public InvoiceDetails.InvoiceTypeCode createInvoiceDetailsInvoiceTypeCode() {
        return new InvoiceDetails.InvoiceTypeCode();
    }

    /**
     * Create an instance of {@link InvoiceDetails.InvoiceDate }
     * 
     */
    public InvoiceDetails.InvoiceDate createInvoiceDetailsInvoiceDate() {
        return new InvoiceDetails.InvoiceDate();
    }

    /**
     * Create an instance of {@link InvoiceDetails.InvoiceTotalVatExcludedAmount }
     * 
     */
    public InvoiceDetails.InvoiceTotalVatExcludedAmount createInvoiceDetailsInvoiceTotalVatExcludedAmount() {
        return new InvoiceDetails.InvoiceTotalVatExcludedAmount();
    }

    /**
     * Create an instance of {@link InvoiceDetails.InvoiceTotalVatAmount }
     * 
     */
    public InvoiceDetails.InvoiceTotalVatAmount createInvoiceDetailsInvoiceTotalVatAmount() {
        return new InvoiceDetails.InvoiceTotalVatAmount();
    }

    /**
     * Create an instance of {@link InvoiceDetails.InvoiceTotalVatIncludedAmount }
     * 
     */
    public InvoiceDetails.InvoiceTotalVatIncludedAmount createInvoiceDetailsInvoiceTotalVatIncludedAmount() {
        return new InvoiceDetails.InvoiceTotalVatIncludedAmount();
    }

    /**
     * Create an instance of {@link InvoiceDetails.PaymentTermsDetails.InvoiceDueDate }
     * 
     */
    public InvoiceDetails.PaymentTermsDetails.InvoiceDueDate createInvoiceDetailsPaymentTermsDetailsInvoiceDueDate() {
        return new InvoiceDetails.PaymentTermsDetails.InvoiceDueDate();
    }

    /**
     * Create an instance of {@link InvoiceDetails.PaymentTermsDetails.PaymentOverDueFineDetails }
     * 
     */
    public InvoiceDetails.PaymentTermsDetails.PaymentOverDueFineDetails createInvoiceDetailsPaymentTermsDetailsPaymentOverDueFineDetails() {
        return new InvoiceDetails.PaymentTermsDetails.PaymentOverDueFineDetails();
    }

    /**
     * Create an instance of {@link DeliveryPartyDetails.DeliveryPostalAddressDetails }
     * 
     */
    public DeliveryPartyDetails.DeliveryPostalAddressDetails createDeliveryPartyDetailsDeliveryPostalAddressDetails() {
        return new DeliveryPartyDetails.DeliveryPostalAddressDetails();
    }

    /**
     * Create an instance of {@link BuyerPartyDetails.BuyerPostalAddressDetails }
     * 
     */
    public BuyerPartyDetails.BuyerPostalAddressDetails createBuyerPartyDetailsBuyerPostalAddressDetails() {
        return new BuyerPartyDetails.BuyerPostalAddressDetails();
    }

}
